platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

project '/Users/zohrath/Coding/Platform/Platform-spanning/iOS/Beerdex/Beerdex.xcodeproj'
target 'Beerdex' do
    pod 'Alamofire'
    
end 